### ISSUE TITLE
Package into RPM

### ISSUE THREAD

**Issue by alex-krash** [ClickHouse/clickhouse-jdbc-bridge#10]
Looks like this plugin might be applicable.
https://github.com/mojohaus/rpm-maven-plugin

**Comment by kimlehi** [comment]
Hi, can you tell me how to use this plugin?

**Comment by songsiqi213** [comment]
同求RPM包

**Comment by beeflyme** [comment]
同求RPM包

**Comment by zhicwu** [comment]
Looks like a task for new feature,  which has been implemented already.
