### ISSUE TITLE
Failed to insert default value

### ISSUE THREAD

**Issue by sliontc** [ClickHouse/clickhouse-jdbc-bridge#109]
I have a jdbc source table without 'operateTime' datetime column and a destination clickhouse table with 'operateTime' column with default value defined like below:

 `operatetime` DateTime DEFAULT now()

The question is when I insert data from select like following:
INSERT INTO ck_table SELECT *
FROM jdbc('msjdbc', 'select * from dbo.jdbc_table')

It always brings out "Code: 20. DB::Exception: Received from 192.168.1.38:9000. DB::Exception: Number of columns doesn't match."

**Comment by zhicwu** [comment]
Why not use `insert into ck_table(<columns>) select *...` or `insert into ck_table select *, now() as operateTime from ...`?
