### ISSUE TITLE
How to use variables inside jdbc query

### ISSUE THREAD

**Issue by arvkonstantin** [ClickHouse/clickhouse-jdbc-bridge#112]
Hello!
This query
`select point from coords limit 1`
returns "(1.0,2.0)"
And i have this query:
`select a.st_astext as point
from
jdbc(
    'postgres13?one=1.0&two=2.0',
    'select st_astext(st_transform(st_setsrid(st_point({{one}}, {{ two }}), 4326), 3857))'
    ) a;`
I want to paste coordinates from clickhouse table to jdbc query. How i can do it?
Thanks

**Comment by zhicwu** [comment]
Well... unfortunately it's beyond what jdbc-bridge is capable of. Perhaps you can try something like https://github.com/Percona-Lab/clickhousedb_fdw and update your query accordingly?
