### ISSUE TITLE
Looks like it's not possible to use docker env for driver download

### ISSUE THREAD

**Issue by UnamedRus** [ClickHouse/clickhouse-jdbc-bridge#135]
clickhouse-jdbc-bridge by default has clickhouse-jdbc-driver in ./drivers dir, which effectively disable driver download.

```
root@9ee0fec413ce:/app# ls ./drivers/
clickhouse-jdbc-0.3.1-patch-shaded.jar
```

https://github.com/ClickHouse/clickhouse-jdbc-bridge/blob/f02b015093a3ef6b159c8ebd5fec1ceca98e0e87/docker/docker-entrypoint.sh#L13

**Comment by zhicwu** [comment]
Thanks @UnamedRus. Actually it is possible when you mount an empty directory. On production, it's better to mount a directory with tested drivers, instead of relying on this function or specifying the driver URL in datasource configuration.

**Comment by UnamedRus** [comment]
I did use workaround with rm -rf /app/drivers/* in cmd.

But i like your approach more.

Thanks
