### ISSUE TITLE
Doesn't work with materialized view

### ISSUE THREAD

**Issue by sliontc** [ClickHouse/clickhouse-jdbc-bridge#137]
I'v tested JDBC engine with materialized view and found out that the view was not refreshed after data inserted into the jdbc table.

Steps:
1. Create Table test ENGINE = JDBC('msjdbc_keyword', 'dbo', 'NewTable') // the datasource is MS SqlServer
2. CREATE MATERIALIZED VIEW mv ENGINE = MergeTree AS SELECT * FROM test
2. Insert into Keyword.dbo.NewTable (name) VALUES('oiljkl')
3. Select * From mv
Result:
No data was returned.

So dose that mean the Materialized View is not supported for the JDBC engine?

**Comment by zhicwu** [comment]
Yes, ClickHouse does not support materialized view over remote table like the one backed by JDBC bridge.

**Comment by sliontc** [comment]
So any plan on this function?
Actually MySQL engine does support.

**Comment by zhicwu** [comment]
I'm not aware of any plan regarding this. Please feel free to submit a feature request in [ClickHouse](/ClickHouse/ClickHouse/issues).

**Comment by sliontc** [comment]
Thanks.
