### ISSUE TITLE
为什么oracle连接不了呢？

### ISSUE THREAD

**Issue by MataSong** [ClickHouse/clickhouse-jdbc-bridge#138]
错误信息: 
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
 . (RECEIVED_ERROR_FROM_REMOTE_IO_SERVER) (version 21.11.5.33 (official build))

**Comment by zhicwu** [comment]
Not sure without any context. Just googled the error and found https://stackoverflow.com/questions/30861061/ora-12505-tns-listener-does-not-currently-know-of-sid-given-in-connect-descript.

Closing as this is irrelevant to JDBC bridge.
