### ISSUE TITLE
clickhouse-client is not responding when server started  with --listen_port

### ISSUE THREAD

**Issue by HeenaBansal2009** [ClickHouse/clickhouse-jdbc-bridge#141]
I started my CH server with --listen_host=<ip>. 
I see that my server is listening on native protocol at <ip>:8123 through net stat output, , but i am unable to connect to clickhouse-client at <ip>:8123

- Commmand to start CH server

`./clickhouse-server --config-file=../../programs/server/config.xml -- --listen_host=9.30.160.51`

- netstat -tulnp | grep LISTEN output :

- ./clickhouse-client connection is hung :

- Server logs 
<img width="1440" alt="Screen Shot 2022-03-08 at 10 23 08 PM" src="https://user-images.githubusercontent.com/86018844/157366673-95a729ee-0071-4f8f-94e9-a430637453b2.png">
<img width="1440" alt="Screen Shot 2022-03-08 at 10 22 45 PM" src="https://user-images.githubusercontent.com/86018844/157366695-fe98655a-0c54-4762-a51c-e00daee90687.png">

**Comment by HeenaBansal2009** [comment]
When I am starting my server with --tcp-port =0 and connect clickhouse-client with port , I can connect clickhouse-client. 
./clickhouse-client  -u default  --host 9.30.160.51 --port 33479 

SERVER STARTED : ./clickhouse-server --config-file=../../programs/server/config.xml --  --listen_host=9.30.160.51 --tcp_port=0

**Comment by zhicwu** [comment]
Hi @HeenaBansal2009, this has nothing to do with JDBC bridge, right?

`clickhouse-client` uses native/tcp protocol to connect to ClickHouse, while port 8123 by default is for http. You may want to check server configuration as well to ensure you connected to correct port.

**Comment by HeenaBansal2009** [comment]
Right,I opened the issue in wrong repo. Can be closed.
