### ISSUE TITLE
Question: How to prevent repeated execution for a wrong query?

### ISSUE THREAD

**Issue by alex-bochkov** [ClickHouse/clickhouse-jdbc-bridge#147]
Is there a way to prevent repeated query execution when it fails?
Currently, clickhouse-jdbc-bridge retries the query 10 times before returning the failure to the client. 
(sorry, I couldn't find any parameters in the config).

![image](https://user-images.githubusercontent.com/13791336/163244027-becf16ef-d01f-422d-a345-eb43e4bdcbd1.png)

**Comment by zhicwu** [comment]
Hi @alex-bochkov, thanks for reporting the issue. I can reproduce the issue using a query like `select * from jdbc('mysql1','a1 String', 'select a1')`. There's a release planned this weekend(primarily to rename packages to com.clickhouse), let me see if I can get it fixed. Meanwhile, I suspect there's issue in your question - you may remove the second parameter for testing, although it may introduce additional query for type inferring.

**Comment by zhicwu** [comment]
Close as it's not an issue with JDBC bridge.
