### ISSUE TITLE
Add support for Oracle JDBC

### ISSUE THREAD

**Issue by Nyamhyy** [ClickHouse/clickhouse-jdbc-bridge#2]
Currently without any code modification it is hard to work with Oracle database. Following problems are encountered:
- Can't pass login and password information to connection. Oracle JDBC requires passing login and password in properties, rather than in connection string. https://razorsql.com/articles/oracle_jdbc_connect.html
- Can't select tables with NUMERIC, NVARCHAR columns
- "ORA-01882: timezone region not found" error
- "Invalid or unsupported name for clientInfo" with new ojdbc8 driver

**Comment by alex-krash** [comment]
Thanks for your feedback!
Can you, please, give me a brief instruction/link, how I can setup an Oracle sandbox, for debugging?
I am absolutely unfamiliar with this DBMS.
On top of that, please provide particular version of ojdbc8, you are using.
Thanks in advance!

**Comment by Nyamhyy** [comment]
Easiest way to setup an Oracle DB is to use docker containers. You can use one of the following images:
- https://hub.docker.com/r/sath89/oracle-12c/
- https://hub.docker.com/r/wnameless/oracle-xe-11g/

I'm using JDBC driver from this page: https://www.oracle.com/technetwork/database/application-development/jdbc/downloads/jdbc-ucp-183-5013470.html

**Comment by akonyaev90** [comment]
I started work on this

**Comment by zhicwu** [comment]
Close as this seems been fixed earlier.
