### ISSUE TITLE
jdbc postgres fail

### ISSUE THREAD

**Issue by AymanElarian** [ClickHouse/clickhouse-jdbc-bridge#24]
hello ,  jdbc bridage fail for postgres driver as the following 

Code: 86. DB::Exception: Received from localhost:9000. DB::Exception: Received error from remote server /identifier_quote?connection_string=jdbc%3Apostgresql%3A%2F%2Fttc-...... HTTP status code: 500 Server Error, body: No suitable driver found for jdbc:postgresql://.......

**Comment by xchf** [comment]
Download postgresql-42.2.5.jar

**Comment by RainDong911** [comment]
Where to put the driver jar files?

**Comment by aorashi** [comment]
/var/lib/clickhouse-jdbc-bridge
or 
change in  default config BRIDGE_DRIVER_DIR  variable

**Comment by zhicwu** [comment]
Close as this looks like a configuration issue,  not a defect in code.
