### ISSUE TITLE
Postgresql array type mapping support?

### ISSUE THREAD

**Issue by yytsui** [ClickHouse/clickhouse-jdbc-bridge#65]
An exception was raised  while trying  to select some rows from a PostgreSQL table:

`java.sql.SQLException: Can not map SQL type 2003 (ARRAY) to ClickHouse`

even if I just a non-array column.

I'm assuming the ARRAY type is not support as of today, as I compiled the jar from the git repo master branch.

_Clickhouse ver: 20.9.3.45
OS: Debian 10
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
JDBC drive: postgresql-42.2.18.jar_

**Comment by zhicwu** [comment]
Array is an advanced type that is supported at this point. I'm working on 2.0 and let me see if this can be added. In worst case,  it will be mapped as String in clickhouse.

**Comment by zhicwu** [comment]
Array or any other unsupported data types are treated as String in 2.0.0.

I created #88 to track this issue and will provide better solution in 2.1.
