### ISSUE TITLE
Exception thrown after insertion

### ISSUE THREAD

**Issue by sliontc** [ClickHouse/clickhouse-jdbc-bridge#83]
![QQ20210108-213336](https://user-images.githubusercontent.com/6959147/104021208-5b930380-51f9-11eb-9e10-af7e7dca2cd4.png)
How to get this fixed?

**Comment by zhicwu** [comment]
Can you increase max execution time in `config/vertx.json`?

**Comment by sliontc** [comment]
> Can you increase max execution time in `config/vertx.json`?

I didn't use that configuration. My usecase is inserting data into jdbc table engine.

**Comment by zhicwu** [comment]
Are you using docker? Regardless, you can take [this](../blob/master/docker/config/vertx.json) as an example, put `config/vertx.json` under your work directory(e.g. /app/config/vertx.json in docker container).

**Comment by sliontc** [comment]
> Are you using docker? Regardless, you can take [this](../blob/master/docker/config/vertx.json) as an example, put `config/vertx.json` under your work directory(e.g. /app/config/vertx.json in docker container).

No, I use Java CLI after building your git repo. Here is my datasource config.
![image](https://user-images.githubusercontent.com/6959147/104033355-6013e800-520a-11eb-8ff6-6541294f9d75.png)
Seems vertx.json is not used.

**Comment by sliontc** [comment]
![image](https://user-images.githubusercontent.com/6959147/104033492-8cc7ff80-520a-11eb-97ac-bd5adf6b6e6b.png)
The insert is almost done.

**Comment by zhicwu** [comment]
> Seems vertx.json is not used.

You can create the file if it does not exist.

**Comment by sliontc** [comment]
> > Seems vertx.json is not used.
> 
> You can create the file if it does not exist.

I created the file vertx.json:

{
  "maxEventLoopExecuteTime": 15,
  "maxEventLoopExecuteTimeUnit": "SECONDS",
  "maxWorkerExecuteTime": 3000,
  "maxWorkerExecuteTimeUnit": "SECONDS",
  "workerPoolSize": 20
}

But it failed with different error:
![image](https://user-images.githubusercontent.com/6959147/104285715-fa1baf00-54ee-11eb-995b-117d04b6f4fc.png)
![image](https://user-images.githubusercontent.com/6959147/104285825-22a3a900-54ef-11eb-8696-20397b7f0439.png)

**Comment by sliontc** [comment]
If I insert select top 100 records, it run successfully.

**Comment by zhicwu** [comment]
What's the log level in your `log4j.properties`? You may hit the error when trace level is enabled. Can you edit the file in your clickhouse-jdbc-bridge jar file by changing log level to `WARN` or `ERROR`?

**Comment by sliontc** [comment]
> What's the log level in your `log4j.properties`? You may hit the error when trace level is enabled. Can you edit the file in your clickhouse-jdbc-bridge jar file by changing log level to `WARN` or `ERROR`?
> 
> Alternatively, you can use [this new build](https://github.com/zhicwu/clickhouse-jdbc-bridge/releases/download/v2.0.0/clickhouse-jdbc-bridge-2.0.0.jar), which turned off debug log causing the problem.

Your log4j.properties is same with mine like below:

log4j.rootLogger=DEBUG, STDOUT
log4j.category.ru.yandex.clickhouse=WARN
log4j.category.ru.yandex.clickhouse.jdbcbridge=DEBUG
log4j.category.ru.yandex.clickhouse.jdbcbridge.internal=WARN
log4j.appender.STDOUT=ru.yandex.clickhouse.jdbcbridge.internal.log4j.ConsoleAppender
log4j.appender.STDOUT.layout=ru.yandex.clickhouse.jdbcbridge.internal.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.sss} [%t] [%-5p] {%c{1}:%L} - %m%n

**Comment by zhicwu** [comment]
I see. Did you try the alternative approach? Changing log level to warn/error works too.

**Comment by sliontc** [comment]
> I see. Did you try the alternative approach? Changing log level to warn/error works too.
I use your build and following error:
![image](https://user-images.githubusercontent.com/6959147/104421886-f18eab80-55b6-11eb-8591-31146e232d06.png)

**Comment by sliontc** [comment]
And this is error from CK log:
![image](https://user-images.githubusercontent.com/6959147/104425747-00c42800-55bc-11eb-96b1-5b9e1c716041.png)

**Comment by zhicwu** [comment]
Thank you @sliontc for reporting the issues. From your screenshots, it seems the 2M rows were all inserted into SQL server, but in the end JDBC bridge failed to telling ClickHouse the mutation has been completed. Let me try to fix the issue(and the incorrect `effectedRows` in log) later today. Meanwhile, you may want to verify if all 2,515,081 rows were inserted into SQL server successfully.
```sql
select * from jdbc('<your datasource>', 'select count(1) from t_UnionResource')
```

Moreover, I noticed that the insertion took 470 seconds, so maybe `batch_size`(defaults to 100) can be increased for further improvement.

**Comment by sliontc** [comment]
> Thank you @sliontc for reporting the issues. From your screenshots, it seems the 2M rows were all inserted into SQL server, but in the end JDBC bridge failed to telling ClickHouse the mutation has been completed. Let me try to fix the issue(and the incorrect `effectedRows` in log) later today. Meanwhile, you may want to verify if all 2,515,081 rows were inserted into SQL server successfully.
> 
> ```sql
> select * from jdbc('<your datasource>', 'select count(1) from t_UnionResource')
> ```
> 
> Moreover, I noticed that the insertion took 470 seconds, so maybe `batch_size`(defaults to 100) can be increased for further improvement.

yes, the data were all inserted.

**Comment by sliontc** [comment]
So the bug is fixed?

**Comment by zhicwu** [comment]
Yes, it's been fixed. However, I'm currently having trouble releasing 2.0.0 because of slowness issue on sonatype. I'll try again tomorrow morning and then merge released code into master branch.

Meantime, if you don't want to wait, please follow instructions below:
* build latest code on `develop` branch
  ```bash
  git clone -b develop https://github.com/ClickHouse/clickhouse-jdbc-bridge.git
  cd clickhouse-jdbc-bridge
  mvn -DskipTests -Drevision=2.0.0 clean package
  ```
* use `target/clickhouse-jdbc-bridge-2.0.0-shaded.jar` to replace yours
* create `server.json` based on [this example](https://github.com/ClickHouse/clickhouse-jdbc-bridge/blob/develop/docker/config/server.json#L3) in your work directory - you probably should increase `queryTimeout` to 600000 milliseconds or so
* restart jdbc bridge, truncate your table and start over
  ```sql
  select * from jdbc('<your datasource id>?mutation', 'truncate table dbo.t_UnionResource');
  insert into ...
  ```

**Comment by sliontc** [comment]
Whoo, that's great. You are so awesome.
