### ISSUE TITLE
Does 2.0 support connecting to SparkSQL ?

### ISSUE THREAD

**Issue by 18502907680** [ClickHouse/clickhouse-jdbc-bridge#90]
Does 2.0 support connecting to SparkSQL ?

**Comment by zhicwu** [comment]
Have you tried Hive JDBC driver? Anyway, you can use a working jdbc driver to connect to sparksql. Alternatively, you can put required dependencies into a folder, create a datasource (type=script, driverUrls=<the folder>) and use javascript /groovy to connect to spark sql and issue query.

**Comment by zhicwu** [comment]
Close due to no update more than a week - please feel free to re-open if the issue still exists.
