### ISSUE TITLE
Pushdowns ; Views; 

### ISSUE THREAD

**Issue by bralbral** [ClickHouse/clickhouse-jdbc-bridge#95]
Good day!

> Pushdown is not supported and query may execute twice because of type inferring

Is there issue or limitation? 

`create view my_view as select * from jdbc('connection', 'select * from table')
`
Query 1:
`select * from my_view where a = 1 limit 100`
Query 2:
`select * from jdbc('connection', 'select * from table where a = 1') limit 100` 

Are the queries equals?

Is there a way, in the current implementation, to do some kind of substitution :

`select * from jdbc('conn', 'select * from table where a = {{value}}` ?

Best regards!

**Comment by zhicwu** [comment]
Pushdown is a limitation of the protocol between clickhouse server and jdbc bridge. Only pass-through at this point. I'll submit a proposal to see if the server team can enhance the protocol like they did for mysql table function/engine.

The two queries are different. The filtering happens in clickhouse for the first one, and in your 'connection' data source for the second. If your data source supports `limit`, I'd suggest to change the query to:
```sql
select * from jdbc('connection', 'select * from table where a=1 limit 100') 
```
or below if it does not:
```sql
select * from jdbc('connection?fetch_size=100&max_rows=100', 'select * from table where a=1') 
```

Yes, jdbc bridge supports substitution by using query parameter like below:
```sql
select * from jdbc('conn?value=1', 'select * from table where a={{ value }}') 
```

**Comment by bralbral** [comment]
Thank you!
