### ISSUE TITLE
What's difference between clickhouse-jdbc and clickhouse-jdbc-bridge?

### ISSUE THREAD

**Issue by vleyong** [ClickHouse/clickhouse-jdbc-bridge#99]
I am  so puzzled why clickhouse adds another "clickhouse-jdbc-bridge" tool after providing a clickhouse-jdbc? For example I  need transport SQL Server table data into clickhouse,which project  is better choice。Thanks

**Comment by zhicwu** [comment]
It's better to use `clickhouse-jdbc-bridge`, because it's a bi-directional bridge for transferring data between ClickHouse and other databases. `clickhouse-jdbc` on the other hand is a [type 4 JDBC drvier](https://en.wikipedia.org/wiki/JDBC_driver#Type_4_driver_%E2%80%93_Database-Protocol_driver/Thin_Driver(Pure_Java_driver)) for Java applications - you can use it in DBeaver to connect to ClickHouse.

**Comment by vleyong** [comment]
> It's better to use `clickhouse-jdbc-bridge`, because it's a bi-directional bridge for transferring data between ClickHouse and other databases. `clickhouse-jdbc` on the other hand is a [type 4 JDBC drvier](https://en.wikipedia.org/wiki/JDBC_driver#Type_4_driver_%E2%80%93_Database-Protocol_driver/Thin_Driver(Pure_Java_driver)) for Java applications - you can use it in DBeaver to connect to ClickHouse.

Thanks. So  if I wana use some tools like DBeaver to operate CK. I should use JDBC Not Bridge,dosen`t it?

**Comment by zhicwu** [comment]
> Thanks. So if I wana use some tools like DBeaver to operate CK. I should use JDBC Not Bridge,dosen`t it?

Correct.

**Comment by vleyong** [comment]
> > Thanks. So if I wana use some tools like DBeaver to operate CK. I should use JDBC Not Bridge,dosen`t it?
> 
> Corre

> > Thanks. So if I wana use some tools like DBeaver to operate CK. I should use JDBC Not Bridge,dosen`t it?
> 
> Correct.

You just saved my day.May I ask you one more question?If I have a big wild table in SQL Server ,When importing data to the Clickhouse, what should I do to avoid creating thousands of fields, because the workload is very heavy.

**Comment by zhicwu** [comment]
> You just saved my day.May I ask you one more question?If I have a big wide table in SQL Server ,When importing data to the Clickhouse, what should I do to avoid creating thousands of fields, because the workload is very heavy.

You may try below query to get the table created automatically:
```sql
create table test_table engine=Memory as select * from jdbc('my-sql-server', 'select top 1 * from my.table');
```

With that, you can dump DDL of the `test_table`, make changes(e.g. change to MergeTree engine etc.) as needed, create a new table, and then import data from SQL server:
```sql
drop table if exists test_table;
create table new_table...;
insert into new_table select * from jdbc('my-sql-server', 'select * from my.table');
```

**Comment by vleyong** [comment]
> > You just saved my day.May I ask you one more question?If I have a big wide table in SQL Server ,When importing data to the Clickhouse, what should I do to avoid creating thousands of fields, because the workload is very heavy.
> 
> You may try below query to get the table created automatically:
> 
> ```sql
> create table test_table engine=Memory as select * from jdbc('my-sql-server', 'select top 1 * from my.table');
> ```
> 
> With that, you can dump DDL of the `test_table`, make changes(e.g. change to MergeTree engine etc.) as needed, create a new table, and then import data from SQL server:
> 
> ```sql
> drop table if exists test_table;
> create table new_table...;
> insert into new_table select * from jdbc('my-sql-server', 'select * from my.table');
> ```

Thank you
